version: "3.8"
services:

  controller:
    build: .

  mario:
    build: https://github.com/tehZevo/aegis-mario.git
    environment:
      ACTIONS: "COMPLEX_MOVEMENT"

  ppo:
    build: https://github.com/tehZevo/aegis-ppo.git
    volumes:
      - "./models:/app/models"
    environment:
      MODEL_PATH: "models/ppo"
      #mobilenet_v2 returns 1280-long feature vectors
      OBS_SHAPE: "[1280]"
      #"12" for complex movement
      ACTION_SHAPE: "[12]"

  feature-extractor:
    build: https://github.com/tehZevo/aegis-keras-app.git

  viz:
    build: https://github.com/tehZevo/aegis-visualizer.git
    ports:
      - "8090:80"
