version: "3.8"
services:

  controller:
    build: .

  env:
    build: https://github.com/tehZevo/aegis-vanilla-env.git
    environment:
      ENV_NAME: "LunarLanderContinuous-v2"

  agent:
    build: https://github.com/tehZevo/aegis-ppo.git
    volumes:
      - "./models:/app/models"
    environment:
      MODEL_PATH: "models/ppo"
      OBS_SHAPE: "TODO"
      ACTION_SHAPE: "TODO"
