version: "3.8"
services:

  random-search:
    build: https://github.com/tehZevo/aegis-random-search.git
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
      #mount target build context
      - "./search-target:/target"
    environment:
      NUM_WORKERS: 4
      EXPERIMENT_NAME: "recurrent-ppo"
      TENSORBOARD_LOGGER_URL: "http://logger"
      #OBS+8 from lunar lander
      #ACTION+2 from lunar lander
      PARAMS: |
        META_MEMORY:
          - {"MEMORY_SIZE":0, "AGENT_OBS":8, "AGENT_ACTION":2}
          - {"MEMORY_SIZE":8, "AGENT_OBS":16, "AGENT_ACTION":10}
          - {"MEMORY_SIZE":32, "AGENT_OBS":40, "AGENT_ACTION":34}
        BLACKOUT_RATE: [0, 0.5, 0.9]

  logger:
    build: https://github.com/tehZevo/aegis-tensorboard.git
    volumes:
      - "./tensorboard:/app/runs"

  tensorboard:
    image: tensorflow/tensorflow
    volumes:
      - "./tensorboard:/runs"
    ports:
      - "6006:6006"
    command: "tensorboard --logdir /runs --bind_all"
